# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d806cf841a33a7eafa2d3e087585f4529254c8119547cdff622dc57c0085db9eb98ea8f33ed0efc5e2b26e9f94fef428df61498b42e7a9001c7f12c27b05d9ea

test:
  secret_key_base: 6bc1c57aea2347a1423f02cb2a586070c38f2c674dc03ad7b8a0297ff88ddeee6087bc8c02d0eaff59fe87ebd4a57460a1b62398ff78fb9940234f714982a78b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
